
export const CERRAR_SESION = 'CERRAR_SESION';
export const LOGIN_EXITOSO       = 'LOGIN_EXITOSO';
export const LOGIN_ERROR         = 'LOGIN_ERROR';

export const LIMPIAR_REGISTRO    = 'LIMPIAR_REGISTRO';


export const REGISTRO_ERROR      = 'REGISTRO_ERROR';
export const REGISTRO_EXITOSO    = 'REGISTRO_EXITOSO';
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';


