export const LIMPIAR_REGISTRO    = 'LIMPIAR_REGISTRO';
export const REGISTRO_ERROR      = 'REGISTRO_ERROR';
export const REGISTRO_EXITOSO    = 'REGISTRO_EXITOSO';
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';


